= Relaton::Plateau: retrieve Project PLATEAU Standards for bibliographic use using the ItemData model

[NOTE]
====
`relaton-plateau` is distributed as part of the combined `relaton` gem and is no longer published as a standalone gem.
Install `relaton` (it bundles every flavor, loaded lazily) instead of
`relaton-plateau`. This directory is the gem's development home in the
https://github.com/relaton/relaton[relaton monorepo].
====

image:https://img.shields.io/gem/v/relaton-plateau.svg["Gem Version", link="https://rubygems.org/gems/relaton-plateau"]
image:https://github.com/relaton/relaton-plateau/workflows/macos/badge.svg["Build Status (macOS)", link="https://github.com/relaton/relaton-plateau/actions?workflow=macos"]
image:https://github.com/relaton/relaton-plateau/workflows/windows/badge.svg["Build Status (Windows)", link="https://github.com/relaton/relaton-plateau/actions?workflow=windows"]
image:https://github.com/relaton/relaton-plateau/workflows/ubuntu/badge.svg["Build Status (Ubuntu)", link="https://github.com/relaton/relaton-plateau/actions?workflow=ubuntu"]
image:https://codeclimate.com/github/relaton/relaton-plateau/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/relaton/relaton-plateau"]
image:https://img.shields.io/github/issues-pr-raw/relaton/relaton-plateau.svg["Pull Requests", link="https://github.com/relaton/relaton-plateau/pulls"]
image:https://img.shields.io/github/commits-since/relaton/relaton/latest.svg["Commits since latest",link="https://github.com/relaton/relaton-plateau/releases"]

RelatonPlateau is a Ruby gem that implements the https://github.com/relaton/relaton-model-plateau[ItemData model].

You can use it to retrieve metadata of Plateau Standards from the GitHub repository, and access such metadata through the `Relaton::Plateau::ItemData` object.

== Usage

=== Fetching

==== Fetching Technical Reports

[source,ruby]
----
require "relaton/plateau"

Relaton::Plateau::Bibliography.get("PLATEAU Technical Report #00")
[relaton-plateau] INFO: (PLATEAU Technical Report #00) Fetching ...
[relaton-plateau] INFO: (PLATEAU Technical Report #00) Found `PLATEAU Technical Report #00 1.0`
=> #<Relaton::Plateau::ItemData:0x00000001236204e8
...
----

==== Fetching Handbooks unversioned

[source,ruby]
----
Relaton::Plateau::Bibliography.get("PLATEAU Handbook #00")
[relaton-plateau] INFO: (PLATEAU Handbook #00) Fetching ...
[relaton-plateau] INFO: (PLATEAU Handbook #00) Found `PLATEAU Handbook #00`
=> #<Relaton::Plateau::ItemData:0x00000001242bd200
...
----

==== Fetching Handbooks versioned

[source,ruby]
----
bib = Relaton::Plateau::Bibliography.get("PLATEAU Handbook #00 1.0")
[relaton-plateau] INFO: (PLATEAU Handbook #00 1.0) Fetching ...
[relaton-plateau] INFO: (PLATEAU Handbook #00 1.0) Found `PLATEAU Handbook #00 1.0`
=> #<Relaton::Plateau::ItemData:0x0000000124157320
...
----

=== Serializing

==== XML

[source,ruby]
----
puts bib.to_xml
=> "<bibitem id="PLATEAUHandbook0010" type="standard" schema-version="v1.4.1">
      <title language="en" script="Latn" type="main">PLATEAU Guidebook</title>
      <uri type="pdf">https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_doc_0000_ver01.pdf</uri>
      <docidentifier type="PLATEAU" primary="true">PLATEAU Handbook #00 1.0</docidentifier>
      ...
    </bibitem>"

puts bib.to_xml bibdata: true
=> "<bibdata type="standard" schema-version="v1.4.1">
      <title language="en" script="Latn" type="main">PLATEAU Guidebook</title>
      <uri type="pdf">https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_doc_0000_ver01.pdf</uri>
      <docidentifier type="PLATEAU" primary="true">PLATEAU Handbook #00 1.0</docidentifier>
      ...
      <ext schema-version="v0.0.2">
        <doctype>handbook</doctype>
        <flavor>plateau</flavor>
        <structuredidentifier type="Handbook">
          <agency>PLATEAU</agency>
          <docnumber>00</docnumber>
          <edition>1.0</edition>
        </structuredidentifier>
        <filesize>18381880</filesize>
      </ext>
    </bibdata>"
----

==== YAML

[source,ruby]
----
bib.to_yaml
=> "---
    id: PLATEAUHandbook0010
    type: standard
    schema_version: v1.4.1
    ..."
----

=== Create from XML

[source,ruby]
----
Relaton::Plateau::Item.from_xml File.read("spec/fixtures/handbook.xml")
=> #<Relaton::Plateau::ItemData:0x0000000123b99118
...
----

=== Create from YAML

[source,ruby]
----
Relaton::Plateau::Item.from_yaml File.read("spec/fixtures/item.yaml")
=> #<Relaton::Plateau::ItemData:0x00000001209fd208
...
----

=== Fetching data

Two datasets are available for fetching: `plateau-handbooks` and `plateau-technical-reports`. The format can be `xml`, `yaml`, or `bibxml`.

[source,ruby]
----
require "relaton/plateau/data_fetcher"

Relaton::Plateau::DataFetcher.fetch("plateau-handbooks", output: "dir", format: "xml")
Started at: 2026-03-02 15:36:03 -0500
Stopped at: 2026-03-02 15:36:04 -0500
Done in: 1 sec.
----

== Logging

RelatonPlateau uses https://github.com/relaton/relaton-logger[relaton-logger] for logging. By default, it logs to STDERR. To change the log level and output, use `Relaton.logger_pool` and `Relaton.logger`.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `bundle exec rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To update the index test fixture (used by tests), run `rake spec:update_index`. This downloads the latest `index-v1.zip` from the https://github.com/relaton/relaton-data-plateau[relaton-data-plateau] repository.

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/relaton/relaton-plateau

== License

The gem is available as open source under the terms of the https://opensource.org/licenses/MIT[MIT license].
