= Relaton OIML

RelatonOiml is a library to fetch bibliographic items for OIML
(International Organization of Legal Metrology) publications from the
https://github.com/relaton/relaton-data-oiml[relaton-data-oiml] repository.
The result is a Relaton bibliographic item that can be serialised to Relaton
XML or YAML.

It is a part of the https://github.com/relaton/relaton[Relaton] project.

== Supported document types

OIML publications are identified with https://github.com/metanorma/pubid[pubid]
(`Pubid::Oiml`). The following document types are covered:

* Recommendations (`R`)
* Documents (`D`)
* Guides (`G`)
* Vocabularies (`V`)
* Basic Publications (`B`)
* Expert Reports (`E`)
* Seminar Reports (`S`)

== Usage

=== Search for a standard using keywords

[source,ruby]
----
require "relaton/oiml"

item = Relaton::Oiml::Bibliography.get "OIML R 138"
# [relaton-oiml] INFO: (OIML R 138) Fetching from Relaton repository ...
# [relaton-oiml] INFO: (OIML R 138) Found: `OIML R 138:2007`
=> #<Relaton::Oiml::Item:0x...>

item.docidentifier.first.content
=> "OIML R 138:2007"
----

A specific edition and language can be requested:

[source,ruby]
----
Relaton::Oiml::Bibliography.get "OIML R 138:2007 (E)"
----

=== Serialization

[source,ruby]
----
item.to_xml bibdata: true
item.to_yaml
----

== OIML-specific metadata

Enhanced OIML Recommendations carry additional structured metadata exposed via
the bibliographic item extension (`item.ext`):

* `scope`
* `quantity`
* `measuring_instrument`
* `focus_area`
* `sustainability_framework`
* `doi`

== License

Copyright Ribose. BSD 2-clause licensed.
