source "https://rubygems.org"

# Specify your gem's dependencies in gemspec
gemspec

gem "lutaml-model", github: "lutaml/lutaml-model", branch: "main"
gem "relaton-bib", github: "relaton/relaton-bib", branch: "upd-lutaml-model-to-0-8-0"
gem "rfcxml", github: "metanorma/rfcxml", branch: "main"

gem "relaton-3gpp", github: "relaton/relaton-3gpp", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-bipm", github: "relaton/relaton-bipm", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-bsi", github: "relaton/relaton-bsi", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-calconnect", github: "relaton/relaton-calconnect", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-ccsds", github: "relaton/relaton-ccsds", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-cen", github: "relaton/relaton-cen", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-cie", github: "relaton/relaton-cie", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-doi", github: "relaton/relaton-doi", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-ecma", github: "relaton/relaton-ecma", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-etsi", github: "relaton/relaton-etsi", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-gb", github: "relaton/relaton-gb", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-iana", github: "relaton/relaton-iana", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-iec", github: "relaton/relaton-iec", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-ieee", github: "relaton/relaton-ieee", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-ietf", github: "relaton/relaton-ietf", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-iho", github: "relaton/relaton-iho", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-isbn", github: "relaton/relaton-isbn", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-iso", github: "relaton/relaton-iso", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-itu", github: "relaton/relaton-itu", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-jis", github: "relaton/relaton-jis", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-nist", github: "relaton/relaton-nist", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-oasis", github: "relaton/relaton-oasis", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-ogc", github: "relaton/relaton-ogc", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-omg", github: "relaton/relaton-omg", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-plateau", github: "relaton/relaton-plateau", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-un", github: "relaton/relaton-un", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-w3c", github: "relaton/relaton-w3c", branch: "upd-lutaml-model-to-0.8.0"
gem "relaton-xsf", github: "relaton/relaton-xsf", branch: "upd-lutaml-model-to-0.8.0"

gem "byebug"
gem "equivalent-xml", "~> 0.6"
gem "guard", "~> 2.14"
gem "guard-rspec", "~> 4.7"
gem "pry-byebug"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.6"
gem "rubocop"
gem "rubocop-performance"
gem "rubocop-rails"
gem "simplecov", "~> 0.15"
gem "timecop", "~> 0.9"
gem "vcr", "~> 6"
gem "webmock", "~> 3.18"
