# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in relaton_iana.gemspec
gemspec

# Use local monorepo sibling gems where available.
Dir["../*/"].each do |dir|
  name = File.basename(dir)
  next if name == File.basename(__dir__)
  next unless File.exist?(File.join(dir, "#{name}.gemspec"))
  gem name, path: dir
end

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"


gem "equivalent-xml", "~> 0.6"
gem "rubocop", "~> 1.7"
gem "rubocop-performance"
gem "rubocop-rails"
gem "ruby-jing"
gem "simplecov"
gem "vcr"
gem "webmock"
