# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in relaton_etsi.gemspec
gemspec

# Use local monorepo sibling gems where available.
Dir["../*/"].each do |dir|
  name = File.basename(dir)
  next if name == File.basename(__dir__)
  next unless File.exist?(File.join(dir, "#{name}.gemspec"))
  gem name, path: dir
end

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"


gem "equivalent-xml", "~> 0.6"
gem "rubocop", "~> 1.21"
gem "rubocop-performance", "~> 1.19"
gem "rubocop-rails", "~> 2.21"
gem "ruby-jing", "~> 0.0.3"
gem "simplecov", "~> 0.22"
gem "vcr", "~> 6.0"
gem "webmock", "~> 3.19"
