source "https://rubygems.org"

# Specify your gem's dependencies in relaton-bib.gemspec
gemspec

# Use local monorepo sibling gems where available.
Dir["../*/"].each do |dir|
  name = File.basename(dir)
  next if name == File.basename(__dir__)
  next unless File.exist?(File.join(dir, "#{name}.gemspec"))
  gem name, path: dir
end

gem "byebug"
gem "equivalent-xml", "~> 0.6"
gem "openssl", "~> 3.3.2" # 3.3.0 raises error when rubocop fetches https resources
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop"
gem "rubocop-performance"
gem "rubocop-rails"
gem "ruby-jing"
gem "simplecov"
