source "https://rubygems.org"

# Specify your gem's dependencies in gemspec
gemspec

# Use local monorepo sibling gems where available.
Dir["../*/"].each do |dir|
  name = File.basename(dir)
  next if name == File.basename(__dir__)
  next unless File.exist?(File.join(dir, "#{name}.gemspec"))
  gem name, path: dir
end

# https://github.com/rails/rails/issues/55886
# add openssl as an explicit gem to fix SSL verification issues in GHA.
# gem "openssl"

gem "byebug", "~> 11.0"
gem "debug"
gem "equivalent-xml", "~> 0.6"
gem "fiddle"
gem "pry"
gem "rake"
gem "rspec", "~> 3.0"
gem "rspec-command", "~> 1.0.3"
gem "rspec-core", "~> 3.4"
gem "rspec-html", "~> 0.3.0"
gem "simplecov"
gem "vcr"
gem "webmock"
