require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

namespace :spec do
  desc "Download latest OIML index fixture from relaton-data-oiml"
  task :update_index do
    require "net/http"
    require "uri"
    require_relative "lib/relaton/oiml"

    filename = "#{Relaton::Oiml::INDEXFILE}.yaml"
    url = "#{Relaton::Oiml::Bibliography::ENDPOINT}#{filename}"
    dest = File.join(__dir__, "spec", "fixtures", filename)

    puts "Downloading #{url} ..."
    uri = URI.parse(url)
    response = Net::HTTP.get_response(uri)

    if response.is_a?(Net::HTTPSuccess)
      File.binwrite(dest, response.body)
      puts "Updated #{dest} (#{response.body.bytesize} bytes)"
    else
      abort "Failed to download: HTTP #{response.code}"
    end
  end
end
