<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <include href="biblio-standoc.rng">
    <define name="DocumentType">
      <choice>
        <value>interstate</value>
        <value>national</value>
        <value>preliminary</value>
        <value>methodological</value>
      </choice>
    </define>
  </include>
  <define name="BibDataExtensionType" combine="interleave">
    <optional>
      <ref name="urn"/>
    </optional>
    <optional>
      <ref name="webpage"/>
    </optional>
    <optional>
      <ref name="ics_code"/>
    </optional>
    <optional>
      <ref name="developer"/>
    </optional>
    <zeroOrMore>
      <ref name="keywords"/>
    </zeroOrMore>
    <optional>
      <ref name="pages"/>
    </optional>
    <optional>
      <ref name="designation_original"/>
    </optional>
  </define>
  <define name="urn">
    <element name="urn">
      <text/>
    </element>
  </define>
  <define name="webpage">
    <element name="webpage">
      <text/>
    </element>
  </define>
  <define name="ics_code">
    <element name="ics_code">
      <text/>
    </element>
  </define>
  <define name="developer">
    <element name="developer">
      <text/>
    </element>
  </define>
  <define name="keywords">
    <element name="keywords">
      <text/>
    </element>
  </define>
  <define name="pages">
    <element name="pages">
      <text/>
    </element>
  </define>
  <define name="designation_original">
    <element name="designation_original">
      <text/>
    </element>
  </define>
</grammar>
