# frozen_string_literal: true

require "json"
require "fileutils"

module Relaton
  # Assembles the single shippable `relaton` gem from the per-gem source folders
  # under gems/. The per-gem sources are kept as-is (for development and subtree
  # imports); this only vendors their lib/ trees into one staged gem at
  # pkg/combined/ and generates a combined gemspec + an autoload entry file so
  # that `require "relaton"` does not eagerly load every flavor.
  #
  # Which gems are vendored is declared in combined-gems.json (the `combined`
  # list, in load order, base `relaton` first). See `rake build:combined`.
  module CombinedBuilder
    module_function

    CONFIG_FILE = "combined-gems.json"
    STAGE = "pkg/combined"

    # @param root [String] repo root
    # @return [String] path to the staged combined gem
    def build(root: Dir.pwd)
      gems = config(root)
      unless gems.first == "relaton"
        raise "combined list must start with the `relaton` base gem"
      end

      stage = stage_sources(root, gems)
      write_autoload_entry(stage, gems)
      deps = collect_dependencies(root, gems)
      validate_dependencies!(deps)
      write_gemspec(root, stage, deps)
      stage
    end

    # Raise if any merged requirement is unsatisfiable (e.g. two flavors pin a
    # shared dep to disjoint ranges). Without this the build emits a gemspec
    # that only fails later at `bundle install`.
    def validate_dependencies!(deps)
      bad = deps.reject { |_name, req| satisfiable?(req) }
      return if bad.empty?

      lines = bad.map { |name, req| "  #{name}: #{req}" }.join("\n")
      raise "combined build: unsatisfiable dependency constraints:\n#{lines}"
    end

    def config(root)
      JSON.parse(File.read(File.join(root, CONFIG_FILE)))["combined"]
    end

    # Stage the base gem skeleton plus every sibling's lib/ tree. Returns the
    # staged gem dir.
    def stage_sources(root, gems)
      stage = File.join(root, STAGE)
      FileUtils.rm_rf stage
      FileUtils.mkdir_p stage

      seen = {} # staged-relative path => source gem (collision guard)
      stage_base(root, gems.first, stage, seen)
      gems.drop(1).each { |g| vendor_lib(root, g, stage, seen) }
      stage
    end

    # Copy the base `relaton` gem skeleton: lib, bin, LICENSE, README.
    def stage_base(root, base, stage, seen)
      src = File.join(root, "gems", base)
      copy_tree(File.join(src, "lib"), File.join(stage, "lib"), seen, base)
      bin = File.join(src, "bin")
      FileUtils.cp_r(bin, stage) if File.directory?(bin)
      %w[LICENSE README.adoc README.md].each do |f|
        path = File.join(src, f)
        FileUtils.cp(path, stage) if File.file?(path)
      end
    end

    # Vendor one sibling gem's lib/ tree into the combined lib/. Each flavor
    # occupies a disjoint relaton/<flavor>/ subtree, so this never collides.
    def vendor_lib(root, gem, stage, seen)
      copy_tree(File.join(root, "gems", gem, "lib"), File.join(stage, "lib"),
                seen, gem)
    end

    # Recursively copy src_dir into dst_dir, recording every staged file and
    # raising on any overwrite so a real namespace collision fails loudly.
    def copy_tree(src_dir, dst_dir, seen, gem)
      files(src_dir).each do |path|
        rel = path.sub(/\A#{Regexp.escape(src_dir)}\/?/, "")
        guard_collision(seen, rel, gem)
        dst = File.join(dst_dir, rel)
        FileUtils.mkdir_p(File.dirname(dst))
        FileUtils.cp(path, dst)
        seen[rel] = gem
      end
    end

    def files(dir)
      Dir.glob(File.join(dir, "**", "*"), File::FNM_DOTMATCH)
        .reject { |p| File.directory?(p) }
    end

    # relaton.rb is the one path the generator legitimately overwrites later.
    def guard_collision(seen, rel, gem)
      return unless seen.key?(rel) && rel != "relaton.rb"

      raise "combined build collision on lib/#{rel}: " \
            "#{seen[rel]} and #{gem} both provide it"
    end

    # relaton-iso -> Iso, relaton-3gpp -> ThreeGpp, relaton-w3c -> W3c
    def module_token(gem)
      gem.delete_prefix("relaton-").split(/[-_]/).map(&:capitalize)
        .join.sub("3gpp", "ThreeGpp")
    end

    # relaton-iso -> relaton/iso, relaton-3gpp -> relaton/3gpp
    def require_path(gem)
      "relaton/#{gem.delete_prefix('relaton-')}"
    end

    # Generate lib/relaton.rb with an autoload per vendored namespace, so flavor
    # code loads only when its constant is first referenced.
    def write_autoload_entry(stage, gems)
      lines = gems.drop(1).map do |g|
        "  autoload :#{module_token(g)}, #{require_path(g).inspect}"
      end
      File.write(File.join(stage, "lib", "relaton.rb"), <<~RUBY)
        # frozen_string_literal: true

        # Generated by `rake build:combined`. Do not edit by hand.
        # Each flavor namespace is autoloaded: referencing it (or any nested
        # constant) the first time triggers require of that flavor, loading its
        # heavy deps on demand instead of at `require "relaton"`.
        require "relaton/version"

        module Relaton
        #{lines.join("\n")}
        end

        require "relaton/db"
      RUBY
    end

    # Union of every vendored gem's runtime deps, dropping the now-vendored
    # relaton siblings. Conflicting constraints on a dep are intersected (all
    # must hold) and a warning is printed for review.
    # @return [Array<[String, Gem::Requirement]>] sorted by dep name
    def collect_dependencies(root, gems)
      merged = {}
      gems.each do |g|
        runtime_deps(root, g).each { |dep| merge_dependency(merged, dep) }
      end
      merged.sort_by { |name, _| name }
    end

    def runtime_deps(root, gem)
      spec = Gem::Specification.load(File.join(root, "gems", gem,
                                               "#{gem}.gemspec"))
      spec.dependencies.select do |d|
        d.type == :runtime && !/\Arelaton(-|\z)/.match?(d.name)
      end
    end

    def merge_dependency(merged, dep)
      existing = merged[dep.name]
      if existing && existing.to_s != dep.requirement.to_s
        warn "[build:combined] reconciling #{dep.name}: " \
             "#{existing} + #{dep.requirement} (intersection)"
      end
      merged[dep.name] = intersect(existing, dep.requirement)
    end

    def intersect(existing, requirement)
      return requirement unless existing

      Gem::Requirement.new(existing.as_list + requirement.as_list)
    end

    def write_gemspec(root, stage, deps)
      base = Gem::Specification.load(File.join(root, "gems", "relaton",
                                               "relaton.gemspec"))
      File.write(File.join(stage, "relaton.gemspec"),
                 gemspec_source(base, deps))
    end

    # Comparators that set a lower / upper bound, and whether they include it.
    LOWER_OPS = { "=" => true, ">=" => true, ">" => false }.freeze
    UPPER_OPS = { "=" => true, "<=" => true, "<" => false }.freeze

    # Conservative satisfiability check: fold every comparator into a single
    # [low, high] interval and confirm it is non-empty. Operators it cannot
    # interpret are ignored (assumed satisfiable) to avoid false rejections.
    def satisfiable?(requirement)
      acc = { low: nil, low_inc: true, high: nil, high_inc: true }
      requirement.requirements.each { |op, ver| fold_bound(acc, op, ver) }
      interval_nonempty?(acc)
    end

    def fold_bound(acc, oper, ver)
      set_low(acc, ver, LOWER_OPS[oper]) if LOWER_OPS.key?(oper)
      set_high(acc, ver, UPPER_OPS[oper]) if UPPER_OPS.key?(oper)
      return unless oper == "~>"

      set_low(acc, ver, true) # ~> x.y.z == >= x.y.z, < x.(y+1)
      set_high(acc, ver.bump, false)
    end

    def set_low(acc, ver, inc)
      if acc[:low].nil? || ver > acc[:low]
        acc[:low] = ver
        acc[:low_inc] = inc
      elsif ver == acc[:low]
        acc[:low_inc] &&= inc
      end
    end

    def set_high(acc, ver, inc)
      if acc[:high].nil? || ver < acc[:high]
        acc[:high] = ver
        acc[:high_inc] = inc
      elsif ver == acc[:high]
        acc[:high_inc] &&= inc
      end
    end

    def interval_nonempty?(acc)
      low = acc[:low]
      high = acc[:high]
      return true if low.nil? || high.nil?
      return true if low < high

      low == high && acc[:low_inc] && acc[:high_inc]
    end

    def gemspec_source(base, deps) # rubocop:disable Metrics/AbcSize
      dep_lines = deps.map do |name, req|
        "  spec.add_dependency #{name.inspect}, " \
          "#{req.as_list.map(&:inspect).join(', ')}"
      end.join("\n")
      <<~RUBY
        # frozen_string_literal: true

        # Generated by `rake build:combined`. Do not edit by hand.
        Gem::Specification.new do |spec|
          spec.name          = "relaton"
          spec.version       = #{base.version.to_s.inspect}
          spec.authors       = #{base.authors.inspect}
          spec.email         = #{base.email.inspect}
          spec.summary       = #{base.summary.inspect}
          spec.description   = #{base.description.inspect}
          spec.homepage      = #{base.homepage.inspect}
          spec.license       = #{base.license.inspect}

          spec.bindir        = "bin"
          spec.require_paths = ["lib"]
          spec.required_ruby_version = #{base.required_ruby_version.to_s.inspect}
          spec.files = Dir.glob("lib/**/*").select { |f| File.file?(f) } +
                       Dir.glob("bin/**/*").select { |f| File.file?(f) } +
                       %w[LICENSE README.adoc].select { |f| File.file?(f) }

        #{dep_lines}

          spec.metadata["rubygems_mfa_required"] = "true"
        end
      RUBY
    end
  end
end
