source "https://rubygems.org"

# Specify your gem's dependencies in relaton_nist.gemspec
gemspec

# Use local monorepo sibling gems where available.
Dir["../*/"].each do |dir|
  name = File.basename(dir)
  next if name == File.basename(__dir__)
  next unless File.exist?(File.join(dir, "#{name}.gemspec"))
  gem name, path: dir
end


# pubid 2.x lutaml-model index format (to_hash/from_hash) lives on this branch
# until it ships as a gem release; the published alpha's from_hash is broken.
gem "pubid", git: "https://github.com/metanorma/pubid", branch: "rt-new-lutaml-model"

gem "equivalent-xml", "~> 0.6"
gem "pry-byebug"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "ruby-jing"
gem "simplecov"
gem "vcr"
gem "webmock"
