require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

namespace :spec do
  desc "Download latest NIST index fixture (index-v2) from relaton-data-nist"
  task :update_index do
    require "net/http"
    require "uri"

    url = "https://raw.githubusercontent.com/relaton/relaton-data-nist/v2/index-v2.zip"
    dest = File.join(__dir__, "spec", "fixtures", "index-v2.zip")

    puts "Downloading #{url} ..."
    uri = URI.parse(url)
    response = Net::HTTP.get_response(uri)

    if response.is_a?(Net::HTTPSuccess)
      File.binwrite(dest, response.body)
      puts "Updated #{dest} (#{response.body.bytesize} bytes)"
    else
      abort "Failed to download: HTTP #{response.code}"
    end
  end

  desc "Download latest NIST pubs-export fixture from CSRC"
  task :update_pubs_export do
    require "net/http"
    require "uri"

    url = "https://csrc.nist.gov/CSRC/media/feeds/metanorma/pubs-export.zip"
    dest = File.join(__dir__, "spec", "fixtures", "pubs-export.zip")

    puts "Downloading #{url} ..."
    uri = URI.parse(url)
    response = Net::HTTP.get_response(uri)

    if response.is_a?(Net::HTTPSuccess)
      File.binwrite(dest, response.body)
      puts "Updated #{dest} (#{response.body.bytesize} bytes)"
    else
      abort "Failed to download: HTTP #{response.code}"
    end
  end
end
