source "https://rubygems.org"

# Specify your gem's dependencies in gemspec
gemspec

# Use local monorepo sibling gems where available.
Dir["../*/"].each do |dir|
  name = File.basename(dir)
  next if name == File.basename(__dir__)
  next unless File.exist?(File.join(dir, "#{name}.gemspec"))
  gem name, path: dir
end



gem "byebug"
gem "equivalent-xml", "~> 0.6"
gem "guard", "~> 2.14"
gem "guard-rspec", "~> 4.7"
gem "pry-byebug"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.6"
gem "rubocop"
gem "rubocop-performance"
gem "rubocop-rails"
gem "simplecov", "~> 0.15"
gem "timecop", "~> 0.9"
gem "vcr", "~> 6"
gem "webmock", "~> 3.18"
