Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

source "https://rubygems.org"
# Specify your gem's dependencies in relaton_itu.gemspec
gemspec

# Use local monorepo sibling gems where available.
Dir["../*/"].each do |dir|
  name = File.basename(dir)
  next if name == File.basename(__dir__)
  next unless File.exist?(File.join(dir, "#{name}.gemspec"))
  gem name, path: dir
end


gem "equivalent-xml", "~> 0.6"
gem "pry-byebug"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "ruby-jing"
gem "simplecov"
gem "vcr"
gem "webmock"
