name: rake

on:
  push:
    branches: [ main, master ]
    tags: [ v* ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  rake:
    uses: relaton/support/.github/workflows/rake-monorepo.yml@main
    with:
      gem_directory: gems
      ruby_versions: "3.4,4.0"
    secrets:
      pat_token: ${{ secrets.RELATON_CI_PAT_TOKEN }}
